#!/usr/bin/env bash
# add a custom Nginx response header.

# update the packages
sudo apt-get update
sudo apt-get install -y nginx

# creating the index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# performing a redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/EslamElnajdy permanent;"


sudo sed -i "/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# creating a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom http response header
sudo sed -i "server_name_;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# test syntax errors
sudo nginx -t

# Restart
sudo service nginx restart
